### PR TITLE
Implement graphing alg 61 sophia

### PR DESCRIPTION
**Pull request by sophiaabolore**
## Context
---
Created two folders that contain the implementation and display of the Capital and interest graphing as well as the depreciation data graphing. For each folder there are 4 different functions with each corresponding to a specific number of model comparisons. (ie. One model comparison compares a singular model's, like the Honda Civic, new and used vehicle, a two model comparison compares the new and used vehicles of two different models, eg. Honda Civic and Honda Clarity and so on). 

Fixes SE-(Jira Ticket)

### Description

- Graph the Capital and Interest rates for the new and used model of the same car.
- Graph the Depreciation data for the new and used models of the same car. 
- Graph the Capital and Interest rates for the new and used model of two different cars.
- Graph the Depreciation data for the new and used models of two different cars. 
- Graph the Capital and Interest rates for the new and used model of three different cars.
- Graph the Depreciation data for the new and used models of three different cars. 
- Graph the Capital and Interest rates for the new and used model of four different cars.
- Graph the Depreciation data for the new and used models of four different cars. 

### Type of change

Please select options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Can This Be Tested?
---

These graphs are displayed by the line.html file currently, so opening that file should result in the graph being automatically generated with some test inputs. These can be tested with the example inputs that are commented out under each function. The values of those inputs can be changed and the data that appears on the graph should change accordingly.

## Notes:
---

## Checklist:
---

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have given testing instructions for the reviewer 
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] Jira ticket number in PR title

### CODE REVIEW

**Comment by J0pan** [comment]
This is vanilla js, it does not fit into the React framework. Don't merge until we have a resolution.

**Comment by callum-sh** [comment]
Is there a way to add this into a React component? Like can we make it fit.

**Comment by J0pan** [comment]
It does require quite a bit of refactoring, maybe we could host it somewhere else? We should discuss this with Antoine.

**Comment by callum-sh** [comment]
Or is there a way to make the graph save into a png which we can display on the frontend? But then it won't be dynamic?

**Comment by callum-sh** [comment]
Hosting somewhere else seems overly complicated? if we are gunna do that we should have just done it in matplot and switched backend to python. Whole point of keeping backend java was because we could graph in frontend

**Comment by J0pan** [comment]
You're right, we stuck to Java for learning 207 material and graphing.

**Comment by J0pan** [comment]
Antoine said to "add a html page that contains the plain js and add the data as a query parameter".

**Comment by callum-sh** [comment]
Maximizing learning opportunities and outcomes I heard 👌🏼

**Comment by callum-sh** [comment]
also, yea makes sense. Like add the page standalone, not in a react component and then call the page in a react component.

**Comment by J0pan** [comment]
Yeah that's what I was thinking, also Antoine said 'Rewriting graph js to a component might honestly be the easiest'. I'll look into it.

**Pull request merged**
